apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: observer-ai
type: Opaque
data:
  password: <base64-encoded-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: observer-ai
type: Opaque
data:
  jwt-secret: <base64-encoded-jwt-secret>
  google-client-id: <base64-encoded-google-client-id>
  google-client-secret: <base64-encoded-google-client-secret>